### PR TITLE
#129520801 -  User should be able to create a community

### PR DESCRIPTION
**Pull request by andela-hoyeboade**
#### What does this PR do?
It enable users create communities on Codango

#### Description of Task to be completed?
Implement a Create Community view on Codango

#### How should this be manually tested?
- Visit the review app [here](https://codango-staging-pr-151.herokuapp.com)
- Create an account and log in to get to the home page
- On the home page, click the link to create a community (+ icon) located on the community menu
- Fill in the details required and click the Create Community button. A success message will be relayed to you that your community has been created.

#### Screenshots
screen shot 2016-09-06 at 11 03 35
screen shot 2016-09-06 at 11 03 19

#### What are the relevant pivotal tracker stories?
#129520801 -  User should be able to create a community

### CODE REVIEW

**Comment by andela-cobiora** [comment]
@andela-hoyeboade I'm unable to create an account, to test the feature.

**Comment by andela-hoyeboade** [comment]
@andela-cobiora You are not notified when you create an account on Codango. However, you can login with the username and password used to register. You can also login with these credentials
username: test
password: test

**Comment by andela-cobiora** [comment]
PR is looking very good.

Some notes :
- Are there any checks on the community name or can someone use **^&(@U*I#@** as community name?
- Are there any limits to the length of the name and the description?
- For the logo, when we start working with with display it will make sense to have in a particular size for all uploads. is there a check to only allows for this?
- Where we have private(can we indicate that the default is public)?
- Is there a need for the bullet points in the default members permission
- Every user has a default: ability to block members other users, right?

Are these points going to make sense to implement under this ticket or should they be in separate tickets?

**Comment by andela-hoyeboade** [comment]
* For the community name, the field uses a Django CharField and would accept anything so long it is a character. However, we can have some checks to see if the name meets certain requirements like saying it must start with some letters

* There is a limit to the name lenght. It accepts not more than 100 characters. However, the description has no length limit since it is a text field(though it is still possible to set maximum length on a Textfield)

* By the logo, I am not sure if you meant the file size of the image (in terms of bytes) or the display size (in terms of width and height).If you are talking about the file size, the logo field uses a cloudinary field which accepts file not more than 10 MB. However, it is possible to restrict file size before uploading to cloudinary. This can be done with cloudinary  jQuery integration library.
If however, you meant the display size, we can set a default display size for all logo

* The private field can be modified to show that the default is public. Also,the bullet points in the default_members permission would be removed in the updated form. 

* Yes. Every members have the ability to block other members. This would be implemented in the updated form as a default value

And finally. These points can still be implemented under this ticket.
Thanks

**Pull request merged**
